name: Python lint and test action

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip==20.3.1
        pip install pylint --pre --upgrade --upgrade-strategy eager
        pip install pytest pytest-cov
        pip install .
        pylint --version
    - name: Analysing the code with pylint
      run: |
        pylint tsanalysis
    - name: Testing the code with pytest
      run: |
        pytest --cov-report term --cov=tsanalysis tests/